#pragma once
#include "GameObject.h"

#define RIFLEMAN_ANI_NORMAL_LEFT 400
#define RIFLEMAN_ANI_NORMAL_RIGHT 401

#define RIFLEMAN_ANI_SHOOT_LEFT 410
#define RIFLEMAN_ANI_SHOOT_RIGHT 411

#define RIFLEMAN_ANI_AIM_UP_LEFT 420
#define RIFLEMAN_ANI_AIM_UP_RIGHT 421

#define RIFLEMAN_ANI_SHOOT_UP_LEFT 430
#define RIFLEMAN_ANI_SHOOT_UP_RIGHT 431

#define RIFLEMAN_ANI_AIM_DOWN_LEFT 440
#define RIFLEMAN_ANI_AIM_DOWN_RIGHT 441

#define RIFLEMAN_ANI_HIDE_LEFT 450
#define RIFLEMAN_ANI_HIDE_RIGHT 451

#define RIFLEMAN_ANI_EXPOSE_LEFT 460
#define RIFLEMAN_ANI_EXPOSE_RIGHT 461


class Rifleman
{

};

